### PR TITLE
Fix mockery on CI

### PR DESCRIPTION
**Pull request by scothis**
Also treat dependabot builds as PRs.

### CODE REVIEW

**Comment by scothis** [comment]
Looking at this again, mockery wasn't just busted on CI, it was broken everywhere.

**Comment by ericbottard** [comment]
The problem with the change in this PR (and the use of a Makefile var for `MOCKERY`) is that it always rebuilds mocks when running `gen-mocks`, which is what the Makefile was trying to avoid.

Also, I'm getting changes when running `gen-mocks`, is that expected?

**Comment by scothis** [comment]
> The problem with the change in this PR (and the use of a Makefile var for MOCKERY) is that it always rebuilds mocks when running gen-mocks, which is what the Makefile was trying to avoid.

Trying to shave a fraction of a second off a build that is manually triggered wasn't high on my priority list, but it's fixed. But now running `make pkg/proxy/mocks/RiffClient.go` will fail. 🤷‍♂ 

> Also, I'm getting changes when running gen-mocks, is that expected?

I don't have any local changes after running gen-mocks, and CI is passing on the verify step. What version of mockery do you have installed? 1.0.0 is the latest.

**Comment by ericbottard** [comment]
I have the same version (arguably)
```
md5 `which mockery`
MD5 (/Users/ericbottard/Documents/Projects/go/bin/mockery) = c9a769459c556e94fa94b094dbe9406e
```

The changes are related to imports.

**Pull request merged**
